apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: dev-tom
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1V6Q0NBVHNDQVFBd0RqRU1NQW9HQTFVRUF3d0RkRzl0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBN2VkNTZjUTJXUTd2RnR4ZFMvbkViWVBIalpQVTcveFlSVWs2UWFxTE5WenF0VU0rClFFR3pMblEvdTl4WkZuTlRSUWRET0FsNW1saXkxaU56b1hoN0NJcmEvVVZIY2RIRDZCSzNTUkk5eTBjQVRFR0oKZllDbStrWVFaNmsva2hJU25wOENwUE42T3FoeWhuZ01sd3lJcDc2VWVJS2JJSmRRUXQ5YW1lSElkWnM3Y3MrNwphZmNkTjhsOHdQWU03OVR3ckRubWp5Vk9oV2NocTh5RjV0RzdZODNZZjhRTkdjNkFtWDRnRmRiN2JROUQvdDBvClhxcFBQQlYyckIrU3MzaTN4SXNndXo0MmhsOG1kNUtPM0FWSUp0OTZ0N1JTV3pOckY4cW1Ua2Q1dXNqNllvUVcKTmQxTVM2WnIyNDF4bFNrU2pPaFZyZWZnVzQ0Q0RpRUo3ZUZnNHdJREFRQUJvQUF3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFGM0JjdVVIMkJNM2lPZ09UZlNZN00zVkhBOEdYQkozZ0t3Y0N1aTZuNDE4WmpEcUhMK0pmc3UwCkYvOVpqU0UvdmdSRFZsZnJoTTRLdDNVVS9hMHdlaXhjUllkR3lLRTl3ekttY3hGaWdPQkJnUUZRRzB5c2owT04KNFowZnh2bUkwTm9FcitTV0w4ckFvUXJ5U1JKQ3ljM3VHUVlKdUdUYkMzTFErMkUzelpJbTFsNjNGb3JOSVJFZgorVXQwVmt3alEwUjZKeGVXdVhWYzlrazFKYVNzdG5vbE9QYzhURmtXdDBJT2I1MDhaU3BRc1lBRi9PcVN2bjRUCkFSbS9IYXJvWmdTOTAvRzh2Mnlmblc3ZkhNQmRjaFliZzdod0VFSEZORzJwRE9ONFZmUGdqQWN0N2tkMjg2azcKQ2o0YmNCanZPaHNaWE0vcE5jSFUxa1U1bkZ2M2xPcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 8640000 # 100 days
  usages:
  - client auth

